### ISSUE TITLE
Divide-by-zero warnings in optimization notebook

### ISSUE THREAD

**Issue by cosmoharrigan** [jakevdp/2014_fall_ASTR599#4]
For notebook [14](https://github.com/jakevdp/2014_fall_ASTR599/blob/master/notebooks/14_Optimization.ipynb) (optimization), I have used 5 different star IDs with the original notebook, and they produce divide-by-zero warnings in some of the calculations. With the original sample star (`18525697`), there were no such warnings.

To reproduce the warnings, one can use star ID `18870395`. A sample session with the warnings is available [using the notebook viewer here](http://nbviewer.ipython.org/github/cosmoharrigan/2014_fall_ASTR599/blob/error/notebooks/14_Optimization_error.ipynb).

The following warnings are listed after input lines numbers 55, 57 and 60:

```
Divide-by-zero encountered: rhok assumed large
```

```
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/optimize/
optimize.py:828: RuntimeWarning: divide by zero encountered in double_scalars
  rhok = 1.0 / (numpy.dot(yk, sk))
```

I am wondering if these messages have an impact on the resulting calculations?

**Comment by jakevdp** [comment]
I don't think you need to worry about those – rhok will be used in the denominator, so it works out.

**Comment by cosmoharrigan** [comment]
Alright, thanks.
